import type { Metadata } from "next"
import { Inter } from "next/font/google"

import AtomProvider from "./providers/atom-provider"
import ReactQueryProvider from "./providers/react-query-provider"
import MSALProvider from "./providers/msal-provider"
import MSALAuth from "@/components/msal-auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ReactQueryProvider>
          <AtomProvider>
            <MSALProvider>
              <MSALAuth>{children}</MSALAuth>
            </MSALProvider>
          </AtomProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
